# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/miquel/Documents/Q5/A/Supersopa/SuperSopa

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/miquel/Documents/Q5/A/Supersopa/SuperSopa

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/miquel/Documents/Q5/A/Supersopa/SuperSopa/CMakeFiles /home/miquel/Documents/Q5/A/Supersopa/SuperSopa//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/miquel/Documents/Q5/A/Supersopa/SuperSopa/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Projecte_SuperSopa

# Build rule for target.
Projecte_SuperSopa: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Projecte_SuperSopa
.PHONY : Projecte_SuperSopa

# fast build rule for target.
Projecte_SuperSopa/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projecte_SuperSopa.dir/build.make CMakeFiles/Projecte_SuperSopa.dir/build
.PHONY : Projecte_SuperSopa/fast

NodeTrie.o: NodeTrie.cc.o
.PHONY : NodeTrie.o

# target to build an object file
NodeTrie.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projecte_SuperSopa.dir/build.make CMakeFiles/Projecte_SuperSopa.dir/NodeTrie.cc.o
.PHONY : NodeTrie.cc.o

NodeTrie.i: NodeTrie.cc.i
.PHONY : NodeTrie.i

# target to preprocess a source file
NodeTrie.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projecte_SuperSopa.dir/build.make CMakeFiles/Projecte_SuperSopa.dir/NodeTrie.cc.i
.PHONY : NodeTrie.cc.i

NodeTrie.s: NodeTrie.cc.s
.PHONY : NodeTrie.s

# target to generate assembly for a file
NodeTrie.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projecte_SuperSopa.dir/build.make CMakeFiles/Projecte_SuperSopa.dir/NodeTrie.cc.s
.PHONY : NodeTrie.cc.s

Trie.o: Trie.cc.o
.PHONY : Trie.o

# target to build an object file
Trie.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projecte_SuperSopa.dir/build.make CMakeFiles/Projecte_SuperSopa.dir/Trie.cc.o
.PHONY : Trie.cc.o

Trie.i: Trie.cc.i
.PHONY : Trie.i

# target to preprocess a source file
Trie.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projecte_SuperSopa.dir/build.make CMakeFiles/Projecte_SuperSopa.dir/Trie.cc.i
.PHONY : Trie.cc.i

Trie.s: Trie.cc.s
.PHONY : Trie.s

# target to generate assembly for a file
Trie.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projecte_SuperSopa.dir/build.make CMakeFiles/Projecte_SuperSopa.dir/Trie.cc.s
.PHONY : Trie.cc.s

diccBloomFilter.o: diccBloomFilter.cc.o
.PHONY : diccBloomFilter.o

# target to build an object file
diccBloomFilter.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projecte_SuperSopa.dir/build.make CMakeFiles/Projecte_SuperSopa.dir/diccBloomFilter.cc.o
.PHONY : diccBloomFilter.cc.o

diccBloomFilter.i: diccBloomFilter.cc.i
.PHONY : diccBloomFilter.i

# target to preprocess a source file
diccBloomFilter.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projecte_SuperSopa.dir/build.make CMakeFiles/Projecte_SuperSopa.dir/diccBloomFilter.cc.i
.PHONY : diccBloomFilter.cc.i

diccBloomFilter.s: diccBloomFilter.cc.s
.PHONY : diccBloomFilter.s

# target to generate assembly for a file
diccBloomFilter.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projecte_SuperSopa.dir/build.make CMakeFiles/Projecte_SuperSopa.dir/diccBloomFilter.cc.s
.PHONY : diccBloomFilter.cc.s

diccDHashing.o: diccDHashing.cc.o
.PHONY : diccDHashing.o

# target to build an object file
diccDHashing.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projecte_SuperSopa.dir/build.make CMakeFiles/Projecte_SuperSopa.dir/diccDHashing.cc.o
.PHONY : diccDHashing.cc.o

diccDHashing.i: diccDHashing.cc.i
.PHONY : diccDHashing.i

# target to preprocess a source file
diccDHashing.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projecte_SuperSopa.dir/build.make CMakeFiles/Projecte_SuperSopa.dir/diccDHashing.cc.i
.PHONY : diccDHashing.cc.i

diccDHashing.s: diccDHashing.cc.s
.PHONY : diccDHashing.s

# target to generate assembly for a file
diccDHashing.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projecte_SuperSopa.dir/build.make CMakeFiles/Projecte_SuperSopa.dir/diccDHashing.cc.s
.PHONY : diccDHashing.cc.s

diccTrie.o: diccTrie.cc.o
.PHONY : diccTrie.o

# target to build an object file
diccTrie.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projecte_SuperSopa.dir/build.make CMakeFiles/Projecte_SuperSopa.dir/diccTrie.cc.o
.PHONY : diccTrie.cc.o

diccTrie.i: diccTrie.cc.i
.PHONY : diccTrie.i

# target to preprocess a source file
diccTrie.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projecte_SuperSopa.dir/build.make CMakeFiles/Projecte_SuperSopa.dir/diccTrie.cc.i
.PHONY : diccTrie.cc.i

diccTrie.s: diccTrie.cc.s
.PHONY : diccTrie.s

# target to generate assembly for a file
diccTrie.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projecte_SuperSopa.dir/build.make CMakeFiles/Projecte_SuperSopa.dir/diccTrie.cc.s
.PHONY : diccTrie.cc.s

program.o: program.cc.o
.PHONY : program.o

# target to build an object file
program.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projecte_SuperSopa.dir/build.make CMakeFiles/Projecte_SuperSopa.dir/program.cc.o
.PHONY : program.cc.o

program.i: program.cc.i
.PHONY : program.i

# target to preprocess a source file
program.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projecte_SuperSopa.dir/build.make CMakeFiles/Projecte_SuperSopa.dir/program.cc.i
.PHONY : program.cc.i

program.s: program.cc.s
.PHONY : program.s

# target to generate assembly for a file
program.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projecte_SuperSopa.dir/build.make CMakeFiles/Projecte_SuperSopa.dir/program.cc.s
.PHONY : program.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Projecte_SuperSopa"
	@echo "... NodeTrie.o"
	@echo "... NodeTrie.i"
	@echo "... NodeTrie.s"
	@echo "... Trie.o"
	@echo "... Trie.i"
	@echo "... Trie.s"
	@echo "... diccBloomFilter.o"
	@echo "... diccBloomFilter.i"
	@echo "... diccBloomFilter.s"
	@echo "... diccDHashing.o"
	@echo "... diccDHashing.i"
	@echo "... diccDHashing.s"
	@echo "... diccTrie.o"
	@echo "... diccTrie.i"
	@echo "... diccTrie.s"
	@echo "... program.o"
	@echo "... program.i"
	@echo "... program.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

